import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowLeft, CircleHelp, ClipboardList, Droplets, Gauge, MapPin, Wrench } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell, Badge, Card, SectionTitle } from "@/components/AppShell";
import { SearchableSelect } from "@/components/SearchableSelect";
import { useDragonflyData } from "@/hooks/useDragonflyData";

export const Route = createFileRoute("/iot-guide")({
  head: () => ({ meta: [{ title: "คู่มืออุปกรณ์ IoT — EasyPlants" }, { name: "description", content: "วิธีติดตั้ง ใช้งาน บำรุงรักษา และแก้ปัญหาอุปกรณ์ IoT สำหรับสวน" }] }),
  component: IoTGuidePage,
});

type Guide = { title: string; summary: string; install: string[]; routine: { frequency: string; task: string }[]; maintenance: string[]; troubleshooting: { symptom: string; action: string }[]; records: string[] };

const guides: Record<string, Guide> = {
  "Soil moisture": { title: "เซนเซอร์ความชื้นดิน", summary: "ช่วยตัดสินใจให้น้ำจากค่าความชื้นบริเวณราก ไม่ใช่การดูหน้าดินเพียงอย่างเดียว", install: ["เลือกจุดที่แทนสภาพดินของแปลง หลีกเลี่ยงหัวน้ำและพื้นที่น้ำขัง", "ฝังหัววัดในระดับรากตามชนิดพืชและคู่มือผู้ผลิต", "ติดป้ายรหัสแปลง จับคู่เกตเวย์ และบันทึกค่าเริ่มต้นหลังติดตั้ง"], routine: [{ frequency: "ทุกเช้า", task: "ดูแนวโน้มความชื้นเทียบกับค่ากำหนดของแปลง" }, { frequency: "หลังให้น้ำ", task: "ตรวจว่าค่าสูงขึ้นตามเวลาที่ควรเป็น" }, { frequency: "ทุก 2 สัปดาห์แรก", task: "เทียบค่าเซนเซอร์กับสภาพดินจริงและปรับเกณฑ์" }], maintenance: ["เช็ดหัววัดและตรวจสาย/จุดต่อทุกเดือน", "ตรวจแบตเตอรี่หรือแผงพลังงานก่อนฤดูฝน", "ห้ามดึงหัววัดจากสายสื่อสารโดยตรง"], troubleshooting: [{ symptom: "ค่าคงที่นานผิดปกติ", action: "ตรวจการสื่อสาร แบตเตอรี่ และการเสียบหัววัด" }, { symptom: "ค่าต่ำมากหลังให้น้ำ", action: "ตรวจตำแหน่งหัววัด ท่อน้ำ และการรั่วซึมของระบบ" }], records: ["ความชื้นก่อนและหลังให้น้ำ", "รอบให้น้ำ", "การปรับเกณฑ์แจ้งเตือน"] },
  "Weather station": { title: "สถานีอากาศ", summary: "เก็บข้อมูลอากาศเฉพาะจุดในสวน เพื่อใช้จัดตารางงานและเฝ้าระวังโรคหรือภัยพิบัติ", install: ["ตั้งในพื้นที่เปิดโล่ง ไม่ติดกำแพงหรือต้นไม้ใหญ่", "ยึดเสาให้มั่นคงและได้ระดับ", "เชื่อมต่อเครือข่าย ตรวจเวลาอุปกรณ์ และทดสอบค่าฝน/ลม"], routine: [{ frequency: "ทุกเช้า", task: "ดูฝน ลม และความชื้นก่อนวางงานฉีดพ่นหรือเก็บเกี่ยว" }, { frequency: "หลังฝนตก", task: "ตรวจค่าฝนสะสมและสร้างงานตรวจโรคหากความชื้นสูงต่อเนื่อง" }, { frequency: "ทุกสัปดาห์", task: "ตรวจความต่อเนื่องของข้อมูลและพลังงาน" }], maintenance: ["ล้างถ้วยวัดฝนและเช็ดแผงพลังงานทุกเดือน", "ตรวจนก แมลง หรือเศษใบไม้ที่บังเซนเซอร์", "ตรวจความมั่นคงของเสาหลังลมหรือพายุแรง"], troubleshooting: [{ symptom: "ฝนเป็น 0 ต่อเนื่องทั้งที่ฝนตก", action: "ตรวจถ้วยวัดฝนอุดตันและการต่อสาย" }, { symptom: "ข้อมูลขาดหาย", action: "ตรวจสัญญาณ เครือข่าย แบตเตอรี่ และเวลาของอุปกรณ์" }], records: ["ฝนสะสม", "อุณหภูมิ/ความชื้น", "เหตุผลเลื่อนงานจากสภาพอากาศ"] },
  "Flow meter": { title: "มิเตอร์วัดการไหลของน้ำ", summary: "ใช้ติดตามอัตราการไหลและหาอาการท่อรั่ว ไส้กรองตัน หรือวาล์วผิดปกติ", install: ["ติดตั้งตามทิศทางน้ำและเว้นระยะท่อตรงตามคู่มือ", "ทดสอบการรั่วและบันทึกอัตราการไหลปกติของแต่ละโซน", "เชื่อมข้อมูลกับโซนให้น้ำที่ถูกต้องในระบบ"], routine: [{ frequency: "ทุกรอบให้น้ำ", task: "เทียบอัตราการไหลกับค่าปกติของโซน" }, { frequency: "ทุกสัปดาห์", task: "ตรวจความต่างของปริมาณน้ำแต่ละโซน" }, { frequency: "เมื่อมีแจ้งเตือน", task: "สร้างงานตรวจปั๊ม ท่อ วาล์ว และไส้กรอง" }], maintenance: ["ตรวจไส้กรองและคราบตะกอนตามรอบระบบน้ำ", "ตรวจจุดต่อท่อและซีลไม่ให้รั่ว", "ทดสอบความแม่นยำหลังซ่อมท่อหรือเปลี่ยนปั๊ม"], troubleshooting: [{ symptom: "อัตราการไหลต่ำ", action: "ตรวจไส้กรองอุดตัน วาล์วเปิดไม่สุด หรือปั๊ม" }, { symptom: "อัตราการไหลสูงผิดปกติ", action: "ตรวจท่อรั่วหรือวาล์วเปิดผิดโซน" }], records: ["ปริมาณน้ำแต่ละโซน", "เหตุการณ์รั่ว/อุดตัน", "งานบำรุงรักษาระบบน้ำ"] },
  Valve: { title: "วาล์วควบคุมน้ำ", summary: "ใช้แสดงและควบคุมสถานะเปิดปิดของโซนให้น้ำ เมื่อเชื่อมกับระบบที่รองรับ", install: ["ติดตั้งในกล่องกันน้ำและติดป้ายชื่อโซน", "จับคู่ตัวควบคุม ทดสอบเปิดปิดด้วยคนก่อน", "กำหนดสิทธิ์และ rule อัตโนมัติหลังทดสอบความปลอดภัย"], routine: [{ frequency: "ทุกรอบให้น้ำ", task: "ยืนยันสถานะเปิด/ปิดตรงกับแผนงาน" }, { frequency: "ทุกเดือน", task: "ทดสอบการตอบสนองและตรวจสายไฟ" }, { frequency: "ก่อนฤดูใช้งานหนัก", task: "ตรวจซีล กล่องกันน้ำ และแหล่งพลังงาน" }], maintenance: ["รักษากล่องควบคุมให้แห้งและปิดสนิท", "ตรวจสายไฟและขั้วต่อเมื่อเกิดไฟตกหรือฝนหนัก", "บันทึกการทดสอบไว้กับงานบำรุงรักษา"], troubleshooting: [{ symptom: "สั่งเปิดแล้วไม่ตอบสนอง", action: "หยุด automation ตรวจไฟ สัญญาณ และวาล์วหน้างานก่อนสั่งซ้ำ" }, { symptom: "สถานะในระบบไม่ตรงหน้างาน", action: "ตรวจเซนเซอร์ตำแหน่งและตั้งค่าการจับคู่ใหม่" }], records: ["ประวัติเปิด/ปิด", "รอบให้น้ำ", "การซ่อมและทดสอบวาล์ว"] },
};

function IoTGuidePage() {
  const { state } = useDragonflyData();
  const [selectedDeviceId, setSelectedDeviceId] = useState("");
  const [view, setView] = useState<"install" | "routine" | "maintenance" | "troubleshooting">("install");
  const selectedDevice = state.iotDevices.find((device) => device.id === selectedDeviceId) ?? state.iotDevices[0];
  const guide = selectedDevice ? guides[selectedDevice.type] ?? guides["Soil moisture"] : undefined;
  const deviceOptions = useMemo(() => state.iotDevices.map((device) => ({ value: device.id, label: `${device.name} · ${device.plot}` })), [state.iotDevices]);

  return <AppShell title="คู่มืออุปกรณ์ IoT" subtitle="ติดตั้ง ใช้งาน บำรุงรักษา และแก้ปัญหาอุปกรณ์ในสวน">
    <Link to="/iot" className="flex items-center gap-1.5 text-xs font-semibold text-primary"><ArrowLeft className="size-3.5" />กลับไปศูนย์ควบคุม IoT</Link>
    {selectedDevice && guide ? <>
      <Card className="space-y-3 border-primary/30 bg-primary-soft/35"><SearchableSelect label="เลือกอุปกรณ์" options={deviceOptions} value={selectedDevice.id} onChange={setSelectedDeviceId} searchPlaceholder="ค้นหาชื่ออุปกรณ์ รหัส หรือแปลง" /><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-card text-primary"><Gauge className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{guide.title}</p><p className="mt-1 text-xs text-muted-foreground">{selectedDevice.id} · แปลง/จุดติดตั้ง {selectedDevice.plot} · ค่าล่าสุด {selectedDevice.latestReading}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{guide.summary}</p></div><Badge tone={selectedDevice.status === "Online" ? "good" : "bad"}>{selectedDevice.status === "Online" ? "เชื่อมต่อแล้ว" : "ออฟไลน์"}</Badge></div></Card>
      <div className="grid grid-cols-2 gap-2">{([ ["install", "ติดตั้ง"], ["routine", "ใช้งานประจำ"], ["maintenance", "บำรุงรักษา"], ["troubleshooting", "แก้ปัญหา"] ] as const).map(([id, label]) => <button key={id} onClick={() => setView(id)} className={`min-h-10 rounded-lg border px-2 text-xs font-semibold ${view === id ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card"}`}>{label}</button>)}</div>
      {view === "install" ? <GuideList title="ขั้นตอนติดตั้ง" icon={<MapPin className="size-4" />} items={guide.install} /> : null}
      {view === "routine" ? <Card><SectionTitle>รอบใช้งานที่แนะนำ</SectionTitle><div className="mt-3 space-y-3">{guide.routine.map((item) => <div key={item.frequency} className="flex gap-3 border-b border-border pb-3 last:border-0 last:pb-0"><span className="min-w-20 rounded-md bg-primary-soft px-2 py-1 text-center text-[11px] font-semibold text-primary">{item.frequency}</span><p className="text-xs text-muted-foreground">{item.task}</p></div>)}</div></Card> : null}
      {view === "maintenance" ? <GuideList title="รายการบำรุงรักษา" icon={<Wrench className="size-4" />} items={guide.maintenance} footer={`ควรบันทึกข้อมูลเหล่านี้ไว้ใน: ${guide.records.join(" · ")}`} /> : null}
      {view === "troubleshooting" ? <Card><SectionTitle>แก้ปัญหาเบื้องต้น</SectionTitle><div className="mt-3 space-y-3">{guide.troubleshooting.map((item) => <div key={item.symptom} className="rounded-lg border border-border p-3"><p className="flex gap-1.5 text-xs font-semibold text-destructive"><AlertTriangle className="size-3.5 shrink-0" />{item.symptom}</p><p className="mt-1 text-xs text-muted-foreground">{item.action}</p></div>)}</div><p className="mt-3 rounded-lg bg-muted px-3 py-2 text-[11px] text-muted-foreground">หากยังแก้ไม่ได้ ให้สร้างงานบำรุงรักษาและแนบรหัสอุปกรณ์กับภาพหรือบันทึกหน้างาน</p></Card> : null}
    </> : <Card className="py-8 text-center text-sm text-muted-foreground">ยังไม่มีอุปกรณ์ IoT ในสวนนี้</Card>}
    <SectionTitle>เมื่ออุปกรณ์ส่งข้อมูลแล้ว</SectionTitle>
    <Card className="space-y-3"><div className="flex gap-3 text-xs"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary-soft text-primary"><Droplets className="size-4" /></span><p className="text-muted-foreground">ข้อมูลเข้าแดชบอร์ด → ตรวจตามกฎ → แจ้งเตือน → คำแนะนำ → สร้าง Task ให้ทีมตรวจหน้างาน</p></div><div className="flex gap-3 text-xs"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary-soft text-primary"><ClipboardList className="size-4" /></span><p className="text-muted-foreground">เมื่อหัวหน้างานอนุมัติ Task ที่ปิดแล้ว ผลการดูแลจะเข้าสู่ประวัติแปลงและรายงาน</p></div><div className="flex gap-3 text-xs"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary-soft text-primary"><CircleHelp className="size-4" /></span><p className="text-muted-foreground">IoT ช่วยตัดสินใจ แต่ไม่ควรแทนการตรวจหน้างานเมื่อมีความเสี่ยงหรือค่าอ่านผิดปกติ</p></div></Card>
  </AppShell>;
}

function GuideList({ title, icon, items, footer }: { title: string; icon: React.ReactNode; items: string[]; footer?: string }) {
  return <Card><SectionTitle>{title}</SectionTitle><ol className="mt-3 space-y-3">{items.map((item, index) => <li key={item} className="flex gap-2 text-xs text-muted-foreground"><span className="flex size-5 shrink-0 items-center justify-center rounded-full bg-primary-soft text-[10px] font-semibold text-primary">{index + 1}</span>{item}</li>)}</ol>{footer ? <p className="mt-3 border-t border-border pt-3 text-[11px] text-primary">{footer}</p> : null}</Card>;
}
