/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as CropCalendarRouteImport } from './routes/crop-calendar'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as DisasterRouteImport } from './routes/disaster'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FarmProRouteImport } from './routes/farm-pro'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IotRouteImport } from './routes/iot'
import { Route as IotGuideRouteImport } from './routes/iot-guide'
import { Route as MachineryRouteImport } from './routes/machinery'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PlotsRouteImport } from './routes/plots'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as YieldRouteImport } from './routes/yield'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const CropCalendarRoute = CropCalendarRouteImport.update({
  id: '/crop-calendar',
  path: '/crop-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const DisasterRoute = DisasterRouteImport.update({
  id: '/disaster',
  path: '/disaster',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmProRoute = FarmProRouteImport.update({
  id: '/farm-pro',
  path: '/farm-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IotRoute = IotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => rootRouteImport,
} as any)
const IotGuideRoute = IotGuideRouteImport.update({
  id: '/iot-guide',
  path: '/iot-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineryRoute = MachineryRouteImport.update({
  id: '/machinery',
  path: '/machinery',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsRoute = PlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/costs': typeof CostsRoute
  '/crop-calendar': typeof CropCalendarRoute
  '/diagnose': typeof DiagnoseRoute
  '/disaster': typeof DisasterRoute
  '/documents': typeof DocumentsRoute
  '/farm-pro': typeof FarmProRoute
  '/inventory': typeof InventoryRoute
  '/iot': typeof IotRoute
  '/iot-guide': typeof IotGuideRoute
  '/machinery': typeof MachineryRoute
  '/market': typeof MarketRoute
  '/monitor': typeof MonitorRoute
  '/more': typeof MoreRoute
  '/my-work': typeof MyWorkRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/plans': typeof PlansRoute
  '/plots': typeof PlotsRoute
  '/recommend': typeof RecommendRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/traceability': typeof TraceabilityRoute
  '/weather': typeof WeatherRoute
  '/workers': typeof WorkersRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/costs': typeof CostsRoute
  '/crop-calendar': typeof CropCalendarRoute
  '/diagnose': typeof DiagnoseRoute
  '/disaster': typeof DisasterRoute
  '/documents': typeof DocumentsRoute
  '/farm-pro': typeof FarmProRoute
  '/inventory': typeof InventoryRoute
  '/iot': typeof IotRoute
  '/iot-guide': typeof IotGuideRoute
  '/machinery': typeof MachineryRoute
  '/market': typeof MarketRoute
  '/monitor': typeof MonitorRoute
  '/more': typeof MoreRoute
  '/my-work': typeof MyWorkRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/plans': typeof PlansRoute
  '/plots': typeof PlotsRoute
  '/recommend': typeof RecommendRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/traceability': typeof TraceabilityRoute
  '/weather': typeof WeatherRoute
  '/workers': typeof WorkersRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/costs': typeof CostsRoute
  '/crop-calendar': typeof CropCalendarRoute
  '/diagnose': typeof DiagnoseRoute
  '/disaster': typeof DisasterRoute
  '/documents': typeof DocumentsRoute
  '/farm-pro': typeof FarmProRoute
  '/inventory': typeof InventoryRoute
  '/iot': typeof IotRoute
  '/iot-guide': typeof IotGuideRoute
  '/machinery': typeof MachineryRoute
  '/market': typeof MarketRoute
  '/monitor': typeof MonitorRoute
  '/more': typeof MoreRoute
  '/my-work': typeof MyWorkRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/plans': typeof PlansRoute
  '/plots': typeof PlotsRoute
  '/recommend': typeof RecommendRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/traceability': typeof TraceabilityRoute
  '/weather': typeof WeatherRoute
  '/workers': typeof WorkersRoute
  '/yield': typeof YieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/costs'
    | '/crop-calendar'
    | '/diagnose'
    | '/disaster'
    | '/documents'
    | '/farm-pro'
    | '/inventory'
    | '/iot'
    | '/iot-guide'
    | '/machinery'
    | '/market'
    | '/monitor'
    | '/more'
    | '/my-work'
    | '/notifications'
    | '/onboarding'
    | '/operations'
    | '/plans'
    | '/plots'
    | '/recommend'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/weather'
    | '/workers'
    | '/yield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/costs'
    | '/crop-calendar'
    | '/diagnose'
    | '/disaster'
    | '/documents'
    | '/farm-pro'
    | '/inventory'
    | '/iot'
    | '/iot-guide'
    | '/machinery'
    | '/market'
    | '/monitor'
    | '/more'
    | '/my-work'
    | '/notifications'
    | '/onboarding'
    | '/operations'
    | '/plans'
    | '/plots'
    | '/recommend'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/weather'
    | '/workers'
    | '/yield'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/costs'
    | '/crop-calendar'
    | '/diagnose'
    | '/disaster'
    | '/documents'
    | '/farm-pro'
    | '/inventory'
    | '/iot'
    | '/iot-guide'
    | '/machinery'
    | '/market'
    | '/monitor'
    | '/more'
    | '/my-work'
    | '/notifications'
    | '/onboarding'
    | '/operations'
    | '/plans'
    | '/plots'
    | '/recommend'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/weather'
    | '/workers'
    | '/yield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AssistantRoute: typeof AssistantRoute
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  CostsRoute: typeof CostsRoute
  CropCalendarRoute: typeof CropCalendarRoute
  DiagnoseRoute: typeof DiagnoseRoute
  DisasterRoute: typeof DisasterRoute
  DocumentsRoute: typeof DocumentsRoute
  FarmProRoute: typeof FarmProRoute
  InventoryRoute: typeof InventoryRoute
  IotRoute: typeof IotRoute
  IotGuideRoute: typeof IotGuideRoute
  MachineryRoute: typeof MachineryRoute
  MarketRoute: typeof MarketRoute
  MonitorRoute: typeof MonitorRoute
  MoreRoute: typeof MoreRoute
  MyWorkRoute: typeof MyWorkRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OperationsRoute: typeof OperationsRoute
  PlansRoute: typeof PlansRoute
  PlotsRoute: typeof PlotsRoute
  RecommendRoute: typeof RecommendRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TraceabilityRoute: typeof TraceabilityRoute
  WeatherRoute: typeof WeatherRoute
  WorkersRoute: typeof WorkersRoute
  YieldRoute: typeof YieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-calendar': {
      id: '/crop-calendar'
      path: '/crop-calendar'
      fullPath: '/crop-calendar'
      preLoaderRoute: typeof CropCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disaster': {
      id: '/disaster'
      path: '/disaster'
      fullPath: '/disaster'
      preLoaderRoute: typeof DisasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-pro': {
      id: '/farm-pro'
      path: '/farm-pro'
      fullPath: '/farm-pro'
      preLoaderRoute: typeof FarmProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iot': {
      id: '/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof IotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iot-guide': {
      id: '/iot-guide'
      path: '/iot-guide'
      fullPath: '/iot-guide'
      preLoaderRoute: typeof IotGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machinery': {
      id: '/machinery'
      path: '/machinery'
      fullPath: '/machinery'
      preLoaderRoute: typeof MachineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots': {
      id: '/plots'
      path: '/plots'
      fullPath: '/plots'
      preLoaderRoute: typeof PlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AssistantRoute: AssistantRoute,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  CostsRoute: CostsRoute,
  CropCalendarRoute: CropCalendarRoute,
  DiagnoseRoute: DiagnoseRoute,
  DisasterRoute: DisasterRoute,
  DocumentsRoute: DocumentsRoute,
  FarmProRoute: FarmProRoute,
  InventoryRoute: InventoryRoute,
  IotRoute: IotRoute,
  IotGuideRoute: IotGuideRoute,
  MachineryRoute: MachineryRoute,
  MarketRoute: MarketRoute,
  MonitorRoute: MonitorRoute,
  MoreRoute: MoreRoute,
  MyWorkRoute: MyWorkRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OperationsRoute: OperationsRoute,
  PlansRoute: PlansRoute,
  PlotsRoute: PlotsRoute,
  RecommendRoute: RecommendRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TraceabilityRoute: TraceabilityRoute,
  WeatherRoute: WeatherRoute,
  WorkersRoute: WorkersRoute,
  YieldRoute: YieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
